In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Read the data from CSV files.

df1 = pd.read_csv("ilo_usd_male_female_2011_2021.csv")
df1.head()

,Unnamed: 0,country,sex,occupation,year,monthly_earnings_usd,group
0,0,Afghanistan,Male,Total,2014,159.57,T
1,1,Afghanistan,Male,1. Managers,2014,305.60,1
2,2,Afghanistan,Male,2. Professionals,2014,197.08,2
3,3,Afghanistan,Male,3. Technicians and associate professionals,2014,229.72,3
4,4,Afghanistan,Male,4. Clerical support workers,2014,271.34,4

In [3]:
df1.tail()

,Unnamed: 0,country,sex,occupation,year,monthly_earnings_usd,group
14940,14940,Zambia,Female,"6. Skilled agricultural, forestry and fishery ...",2020,61.11,6
14941,14941,Zambia,Female,7. Craft and related trades workers,2020,64.05,7
14942,14942,Zambia,Female,"8. Plant and machine operators, and assemblers",2020,127.72,8
14943,14943,Zambia,Female,9. Elementary occupations,2020,56.49,9
14944,14944,Zambia,Female,0. Armed forces occupations,2020,197.00,0

In [4]:
# Dropping the columnd and saving the new DataFrame
df1 = df1.drop(['Unnamed: 0'], axis=1)

# Verifying
df1.head()

,country,sex,occupation,year,monthly_earnings_usd,group
0,Afghanistan,Male,Total,2014,159.57,T
1,Afghanistan,Male,1. Managers,2014,305.60,1
2,Afghanistan,Male,2. Professionals,2014,197.08,2
3,Afghanistan,Male,3. Technicians and associate professionals,2014,229.72,3
4,Afghanistan,Male,4. Clerical support workers,2014,271.34,4

In [5]:
df1.shape

(14945, 6)

In [6]:
df1['occupation'].value_counts()

Total                                                    1458
4. Clerical support workers                              1404
9. Elementary occupations                                1404
5. Service and sales workers                             1402
2. Professionals                                         1396
7. Craft and related trades workers                      1393
1. Managers                                              1392
3. Technicians and associate professionals               1380
8. Plant and machine operators, and assemblers           1370
6. Skilled agricultural, forestry and fishery workers    1243
0. Armed forces occupations                               663
X. Not elsewhere classified                               440
Name: occupation, dtype: int64

In [7]:
df1['country'].value_counts()

Viet Nam           252
Bolivia            246
France             236
Slovakia           235
Finland            234
                  ...
Montenegro          18
Azerbaijan          18
North Macedonia     18
Madagascar          18
Cape Verde          18
Name: country, Length: 130, dtype: int64

In [8]:
df1['group'].value_counts()

# What do these different groups mean?

T    1458
4    1404
9    1404
5    1402
2    1396
7    1393
1    1392
3    1380
8    1370
6    1243
0     663
X     440
Name: group, dtype: int64

In [9]:
# Import the second DataFrame.

df2 = pd.read_csv("ilo_usd_male_female_skill_levels_2011_2021.csv")
df2.head()

,Unnamed: 0,country,sex,occupation,year,monthly_usd
0,0,Afghanistan,Male,Total,2014,159.57
1,1,Afghanistan,Male,Skill levels 3 and 4 ~ high,2014,216.72
2,2,Afghanistan,Male,Skill level 2 ~ medium,2014,179.93
3,3,Afghanistan,Male,Skill level 1 ~ low,2014,107.88
4,4,Afghanistan,Male,Not elsewhere classified,2014,235.35

In [10]:
# Dropping the column with 
df2 = df2.drop(['Unnamed: 0'], axis=1)

In [11]:
df2.head()

       country   sex                   occupation  year  monthly_usd
0  Afghanistan  Male                        Total  2014       159.57
1  Afghanistan  Male  Skill levels 3 and 4 ~ high  2014       216.72
2  Afghanistan  Male       Skill level 2 ~ medium  2014       179.93
3  Afghanistan  Male          Skill level 1 ~ low  2014       107.88
4  Afghanistan  Male     Not elsewhere classified  2014       235.35

In [12]:
df2['year'].nunique()

11

In [13]:
df2['year'].value_counts()

2019    632
2017    566
2012    559
2013    546
2016    522
2015    506
2020    500
2011    473
2018    465
2014    405
2021    179
Name: year, dtype: int64

In [14]:
# Let's look at Poland as an example.

pl_df2 = df2[df2['country'] == 'Poland']
pl_df2

     country     sex                   occupation  year  monthly_usd
4070  Poland    Male                        Total  2011       291.52
4071  Poland    Male  Skill levels 3 and 4 ~ high  2011       414.74
4072  Poland    Male       Skill level 2 ~ medium  2011       247.81
4073  Poland    Male          Skill level 1 ~ low  2011       179.25
4074  Poland    Male     Not elsewhere classified  2011       388.19
...      ...     ...                          ...   ...          ...
4141  Poland  Female                        Total  2014      1167.84
4142  Poland    Male                        Total  2016      1193.48
4143  Poland  Female                        Total  2016      1007.19
4144  Poland    Male                        Total  2018      1410.13
4145  Poland  Female                        Total  2018      1169.80

[76 rows x 5 columns]

In [15]:
pl_df2['occupation'].value_counts()

Total                          20
Skill level 1 ~ low            14
Not elsewhere classified       14
Skill levels 3 and 4 ~ high    14
Skill level 2 ~ medium         14
Name: occupation, dtype: int64

In [16]:
# Let's look at total income.

pl2t = pl_df2[pl_df2['occupation'] == 'Total']
pl2t

     country     sex occupation  year  monthly_usd
4070  Poland    Male      Total  2011       291.52
4075  Poland  Female      Total  2011       253.54
4080  Poland    Male      Total  2012       271.88
4085  Poland  Female      Total  2012       233.92
4090  Poland    Male      Total  2013       284.93
4095  Poland  Female      Total  2013       244.98
4100  Poland    Male      Total  2015       255.24
4105  Poland  Female      Total  2015       207.49
4110  Poland    Male      Total  2017       265.42
4115  Poland  Female      Total  2017       216.23
4120  Poland    Male      Total  2019       305.87
4125  Poland  Female      Total  2019       251.12
4130  Poland    Male      Total  2020       325.26
4135  Poland  Female      Total  2020       270.00
4140  Poland    Male      Total  2014      1419.22
4141  Poland  Female      Total  2014      1167.84
4142  Poland    Male      Total  2016      1193.48
4143  Poland  Female      Total  2016      1007.19
4144  Poland    Male      Total  2018      1410.13
4145  Poland  Female      Total  2018      1169.80

In [17]:
# Let's look at the total monthly_ysd salary over the years.

pl2t.sort_values(by=['year', 'sex'])

     country     sex occupation  year  monthly_usd
4075  Poland  Female      Total  2011       253.54
4070  Poland    Male      Total  2011       291.52
4085  Poland  Female      Total  2012       233.92
4080  Poland    Male      Total  2012       271.88
4095  Poland  Female      Total  2013       244.98
4090  Poland    Male      Total  2013       284.93
4141  Poland  Female      Total  2014      1167.84
4140  Poland    Male      Total  2014      1419.22
4105  Poland  Female      Total  2015       207.49
4100  Poland    Male      Total  2015       255.24
4143  Poland  Female      Total  2016      1007.19
4142  Poland    Male      Total  2016      1193.48
4115  Poland  Female      Total  2017       216.23
4110  Poland    Male      Total  2017       265.42
4145  Poland  Female      Total  2018      1169.80
4144  Poland    Male      Total  2018      1410.13
4125  Poland  Female      Total  2019       251.12
4120  Poland    Male      Total  2019       305.87
4135  Poland  Female      Total  2020       270.00
4130  Poland    Male      Total  2020       325.26

In [17]:
# The data doesn't look clean - the gaps between 2014, 2016, 2018 look very big compared to other years.
# Let's look at other countries.

df2t = df2[df2['occupation'] == 'Total']
df2t

          country     sex occupation  year  monthly_usd
0     Afghanistan    Male      Total  2014       159.57
5     Afghanistan  Female      Total  2014        96.38
10    Afghanistan    Male      Total  2020       174.96
15    Afghanistan  Female      Total  2020       141.16
20        Albania    Male      Total  2012      3408.75
...           ...     ...        ...   ...          ...
5328       Zambia  Female      Total  2018       260.66
5333       Zambia    Male      Total  2019       242.99
5338       Zambia  Female      Total  2019       196.35
5343       Zambia    Male      Total  2020       168.69
5348       Zambia  Female      Total  2020       151.57

[1635 rows x 5 columns]

In [18]:
# Let's see how many unique years I can see per country.

# Make sure I can see all rows.

pd.set_option('display.max_rows', None)

df2t[['year', 'country']].groupby('country').nunique().reset_index()

                               country  year
0                          Afghanistan     2
1                              Albania     7
2                            Argentina     9
3                              Armenia     8
4                            Australia    10
5                              Austria     9
6                           Azerbaijan     9
7                           Bangladesh     2
8                             Barbados     1
9                              Belarus     4
10                             Belgium    10
11                              Belize     7
12                             Bermuda     2
13                              Bhutan     3
14                             Bolivia    11
15              Bosnia and Herzegovina     8
16                            Botswana     2
17                              Brazil    11
18                   Brunei Darussalam     1
19                            Bulgaria     3
20                        Burkina Faso     1
21                             Burundi     1
22                            Cambodia     7
23                            Cameroon     1
24                              Canada     4
25                          Cape Verde     1
26                                Chad     1
27                               Chile     2
28                            Colombia    10
29                             Comoros     1
30   Congo, Democratic Republic of the     1
31                          Costa Rica    11
32                             Croatia     9
33                              Cyprus     9
34                             Czechia    10
35                       Côte d'Ivoire     2
36                             Denmark     9
37                            Djibouti     1
38                  Dominican Republic    11
39                             Ecuador    11
40                               Egypt     9
41                         El Salvador     9
42                             Estonia    10
43                            Eswatini     1
44                            Ethiopia     1
45                                Fiji     2
46                             Finland    10
47                              France     9
48                              Gambia     2
49                             Georgia     1
50                             Germany     8
51                               Ghana     3
52                              Greece     9
53                           Guatemala    10
54                              Guinea     1
55                       Guinea-Bissau     1
56                              Guyana     2
57                            Honduras    10
58                    Hong Kong, China     6
59                             Hungary    10
60                             Iceland     9
61                               India     2
62                           Indonesia     9
63                             Ireland     9
64                              Israel     7
65                               Italy     8
66                             Jamaica     4
67                              Jordan     5
68                          Kazakhstan     8
69                               Kenya     1
70                  Korea, Republic of    11
71    Lao People's Democratic Republic     1
72                              Latvia    10
73                             Lebanon     1
74                             Lesotho     1
75                           Lithuania     6
76                          Luxembourg     9
77                        Macau, China     8
78                          Madagascar     2
79                              Malawi     1
80                            Malaysia    10
81                            Maldives     2
82                                Mali     7
83                               Malta     8
84                    Marshall Islands     1
85                           Mauritius     9
86                              Mexico    11
87                            Mongolia    10
88                             Myanmar     5
89                             Namibia     5
90                               Nepal     1
91                         Netherlands    10
92                           Nicaragua     2
93                             Nigeria     3
94                              Norway    10
95                            Pakistan     9
96                              Panama    11
97                            Paraguay    11
98                                Peru    11
99                         Philippines    10
100                             Poland    10
101                           Portugal     9
102                              Qatar     9
103                            Romania     9
104                 Russian Federation     5
105                             Rwanda     2
106                            Réunion     1
107                              Samoa     2
108                       Saudi Arabia     6
109                            Senegal     2
110                             Serbia     8
111                       Sierra Leone     1
112                          Singapore    10
113                           Slovakia    10
114                           Slovenia     9
115                       South Africa     8
116                              Spain    10
117                          Sri Lanka     9
118                           Suriname     1
119                             Sweden     9
120                        Switzerland     9
121       Tanzania, United Republic of     2
122                           Thailand     9
123                        Timor-Leste     2
124                               Togo     3
125                              Tonga     1
126                Trinidad and Tobago     6
127                            Türkiye    10
128                             Uganda     2
129                            Ukraine     2
130                     United Kingdom    10
131                      United States    11
132                            Uruguay    10
133                         Uzbekistan     1
134                           Viet Nam    11
135                              Yemen     1
136                             Zambia     4

In [19]:
# Let's find the min and max year for each country.

years_df = df2t[['year', 'country']].groupby('country').agg(['min', 'max']).reset_index()

years_df

# There are 136 countries here.

                               country  year
                                         min   max
0                          Afghanistan  2014  2020
1                              Albania  2012  2020
2                            Argentina  2011  2021
3                              Armenia  2013  2020
4                            Australia  2011  2020
5                              Austria  2011  2020
6                           Azerbaijan  2013  2021
7                           Bangladesh  2016  2017
8                             Barbados  2016  2016
9                              Belarus  2011  2021
10                             Belgium  2011  2020
11                              Belize  2014  2020
12                             Bermuda  2012  2013
13                              Bhutan  2018  2020
14                             Bolivia  2011  2021
15              Bosnia and Herzegovina  2011  2021
16                            Botswana  2019  2020
17                              Brazil  2011  2021
18                   Brunei Darussalam  2014  2014
19                            Bulgaria  2012  2020
20                        Burkina Faso  2018  2018
21                             Burundi  2020  2020
22                            Cambodia  2011  2019
23                            Cameroon  2014  2014
24                              Canada  2011  2014
25                          Cape Verde  2015  2015
26                                Chad  2018  2018
27                               Chile  2019  2020
28                            Colombia  2011  2021
29                             Comoros  2014  2014
30   Congo, Democratic Republic of the  2012  2012
31                          Costa Rica  2011  2021
32                             Croatia  2011  2020
33                              Cyprus  2011  2020
34                             Czechia  2011  2020
35                       Côte d'Ivoire  2017  2019
36                             Denmark  2011  2020
37                            Djibouti  2017  2017
38                  Dominican Republic  2011  2021
39                             Ecuador  2011  2021
40                               Egypt  2011  2020
41                         El Salvador  2011  2019
42                             Estonia  2011  2020
43                            Eswatini  2016  2016
44                            Ethiopia  2013  2013
45                                Fiji  2011  2016
46                             Finland  2011  2020
47                              France  2011  2020
48                              Gambia  2012  2018
49                             Georgia  2017  2017
50                             Germany  2011  2019
51                               Ghana  2013  2017
52                              Greece  2011  2020
53                           Guatemala  2011  2021
54                              Guinea  2019  2019
55                       Guinea-Bissau  2018  2018
56                              Guyana  2018  2019
57                            Honduras  2011  2020
58                    Hong Kong, China  2011  2016
59                             Hungary  2011  2020
60                             Iceland  2011  2019
61                               India  2018  2019
62                           Indonesia  2012  2021
63                             Ireland  2011  2020
64                              Israel  2011  2018
65                               Italy  2011  2019
66                             Jamaica  2011  2014
67                              Jordan  2016  2020
68                          Kazakhstan  2011  2020
69                               Kenya  2019  2019
70                  Korea, Republic of  2011  2021
71    Lao People's Democratic Republic  2017  2017
72                              Latvia  2011  2020
73                             Lebanon  2019  2019
74                             Lesotho  2019  2019
75                           Lithuania  2015  2020
76                          Luxembourg  2011  2020
77                        Macau, China  2011  2018
78                          Madagascar  2012  2015
79                              Malawi  2013  2013
80                            Malaysia  2011  2020
81                            Maldives  2016  2019
82                                Mali  2013  2020
83                               Malta  2011  2020
84                    Marshall Islands  2019  2019
85                           Mauritius  2011  2019
86                              Mexico  2011  2021
87                            Mongolia  2011  2021
88                             Myanmar  2015  2020
89                             Namibia  2012  2018
90                               Nepal  2017  2017
91                         Netherlands  2011  2020
92                           Nicaragua  2012  2014
93                             Nigeria  2011  2019
94                              Norway  2011  2020
95                            Pakistan  2011  2021
96                              Panama  2011  2021
97                            Paraguay  2011  2021
98                                Peru  2011  2021
99                         Philippines  2011  2020
100                             Poland  2011  2020
101                           Portugal  2011  2020
102                              Qatar  2011  2020
103                            Romania  2011  2020
104                 Russian Federation  2011  2019
105                             Rwanda  2014  2017
106                            Réunion  2012  2012
107                              Samoa  2012  2017
108                       Saudi Arabia  2015  2020
109                            Senegal  2018  2019
110                             Serbia  2013  2021
111                       Sierra Leone  2018  2018
112                          Singapore  2011  2020
113                           Slovakia  2011  2020
114                           Slovenia  2011  2020
115                       South Africa  2011  2019
116                              Spain  2011  2020
117                          Sri Lanka  2011  2019
118                           Suriname  2016  2016
119                             Sweden  2011  2020
120                        Switzerland  2011  2020
121       Tanzania, United Republic of  2014  2020
122                           Thailand  2011  2020
123                        Timor-Leste  2013  2016
124                               Togo  2011  2017
125                              Tonga  2018  2018
126                Trinidad and Tobago  2011  2016
127                            Türkiye  2011  2021
128                             Uganda  2012  2017
129                            Ukraine  2012  2016
130                     United Kingdom  2011  2020
131                      United States  2011  2021
132                            Uruguay  2011  2020
133                         Uzbekistan  2021  2021
134                           Viet Nam  2011  2021
135                              Yemen  2014  2014
136                             Zambia  2017  2020

In [22]:
# Let's look at full column names.
years_df.columns

MultiIndex([('country',    ''),
            (   'year', 'min'),
            (   'year', 'max')],
           )

In [32]:
# First, let's list out the countries where I cannot make a comparison due to a single data point.

same_country_df = years_df[years_df[('year', 'min')] == years_df[('year', 'max')]]
# same_country_df['is_same_year'] == True
same_country_df.shape #.value_counts()

# We have 28 countries with the same year.

(28, 3)

In [38]:
# For countries without more than 1 year of data
# I want to see which years have the most data.

same_country_df.sort_values(by=('year', 'max'))

# It looks like no particular year stands out.

                               country  year
                                         min   max
106                            Réunion  2012  2012
30   Congo, Democratic Republic of the  2012  2012
79                              Malawi  2013  2013
44                            Ethiopia  2013  2013
135                              Yemen  2014  2014
18                   Brunei Darussalam  2014  2014
23                            Cameroon  2014  2014
29                             Comoros  2014  2014
25                          Cape Verde  2015  2015
118                           Suriname  2016  2016
8                             Barbados  2016  2016
43                            Eswatini  2016  2016
37                            Djibouti  2017  2017
49                             Georgia  2017  2017
71    Lao People's Democratic Republic  2017  2017
90                               Nepal  2017  2017
125                              Tonga  2018  2018
20                        Burkina Faso  2018  2018
111                       Sierra Leone  2018  2018
26                                Chad  2018  2018
55                       Guinea-Bissau  2018  2018
84                    Marshall Islands  2019  2019
73                             Lebanon  2019  2019
69                               Kenya  2019  2019
74                             Lesotho  2019  2019
54                              Guinea  2019  2019
21                             Burundi  2020  2020
133                         Uzbekistan  2021  2021

In [116]:
# Find countries with two different max and min years.

diff_country_df = years_df[years_df[('year', 'min')] != years_df[('year', 'max')]]

diff_country_df.shape

(109, 3)

In [117]:
diff_country_df

                          country  year
                                    min   max
0                     Afghanistan  2014  2020
1                         Albania  2012  2020
2                       Argentina  2011  2021
3                         Armenia  2013  2020
4                       Australia  2011  2020
5                         Austria  2011  2020
6                      Azerbaijan  2013  2021
7                      Bangladesh  2016  2017
9                         Belarus  2011  2021
10                        Belgium  2011  2020
11                         Belize  2014  2020
12                        Bermuda  2012  2013
13                         Bhutan  2018  2020
14                        Bolivia  2011  2021
15         Bosnia and Herzegovina  2011  2021
16                       Botswana  2019  2020
17                         Brazil  2011  2021
19                       Bulgaria  2012  2020
22                       Cambodia  2011  2019
24                         Canada  2011  2014
27                          Chile  2019  2020
28                       Colombia  2011  2021
31                     Costa Rica  2011  2021
32                        Croatia  2011  2020
33                         Cyprus  2011  2020
34                        Czechia  2011  2020
35                  Côte d'Ivoire  2017  2019
36                        Denmark  2011  2020
38             Dominican Republic  2011  2021
39                        Ecuador  2011  2021
40                          Egypt  2011  2020
41                    El Salvador  2011  2019
42                        Estonia  2011  2020
45                           Fiji  2011  2016
46                        Finland  2011  2020
47                         France  2011  2020
48                         Gambia  2012  2018
50                        Germany  2011  2019
51                          Ghana  2013  2017
52                         Greece  2011  2020
53                      Guatemala  2011  2021
56                         Guyana  2018  2019
57                       Honduras  2011  2020
58               Hong Kong, China  2011  2016
59                        Hungary  2011  2020
60                        Iceland  2011  2019
61                          India  2018  2019
62                      Indonesia  2012  2021
63                        Ireland  2011  2020
64                         Israel  2011  2018
65                          Italy  2011  2019
66                        Jamaica  2011  2014
67                         Jordan  2016  2020
68                     Kazakhstan  2011  2020
70             Korea, Republic of  2011  2021
72                         Latvia  2011  2020
75                      Lithuania  2015  2020
76                     Luxembourg  2011  2020
77                   Macau, China  2011  2018
78                     Madagascar  2012  2015
80                       Malaysia  2011  2020
81                       Maldives  2016  2019
82                           Mali  2013  2020
83                          Malta  2011  2020
85                      Mauritius  2011  2019
86                         Mexico  2011  2021
87                       Mongolia  2011  2021
88                        Myanmar  2015  2020
89                        Namibia  2012  2018
91                    Netherlands  2011  2020
92                      Nicaragua  2012  2014
93                        Nigeria  2011  2019
94                         Norway  2011  2020
95                       Pakistan  2011  2021
96                         Panama  2011  2021
97                       Paraguay  2011  2021
98                           Peru  2011  2021
99                    Philippines  2011  2020
100                        Poland  2011  2020
101                      Portugal  2011  2020
102                         Qatar  2011  2020
103                       Romania  2011  2020
104            Russian Federation  2011  2019
105                        Rwanda  2014  2017
107                         Samoa  2012  2017
108                  Saudi Arabia  2015  2020
109                       Senegal  2018  2019
110                        Serbia  2013  2021
112                     Singapore  2011  2020
113                      Slovakia  2011  2020
114                      Slovenia  2011  2020
115                  South Africa  2011  2019
116                         Spain  2011  2020
117                     Sri Lanka  2011  2019
119                        Sweden  2011  2020
120                   Switzerland  2011  2020
121  Tanzania, United Republic of  2014  2020
122                      Thailand  2011  2020
123                   Timor-Leste  2013  2016
124                          Togo  2011  2017
126           Trinidad and Tobago  2011  2016
127                       Türkiye  2011  2021
128                        Uganda  2012  2017
129                       Ukraine  2012  2016
130                United Kingdom  2011  2020
131                 United States  2011  2021
132                       Uruguay  2011  2020
134                      Viet Nam  2011  2021
136                        Zambia  2017  2020

In [43]:
# Getting rid of the occupation column as it seems redundant.

# Creating 2 DataFrames: one for males and one for females.
df2t2 = df2t[['country', 'sex', 'year', 'monthly_usd']]
df2t2_male = df2t2[df2t2['sex'] == 'Male']
df2t2_female = df2t2[df2t2['sex'] == 'Female']

In [54]:
# Joining both DataFrames on country and year.
# This will allow me to see monthly_usd side-by-side and allow me to easily do the ratio calculation.

df2t2_joint = df2t2_female.merge(df2t2_male, on=['country' ,'year'], suffixes=('_female', '_male'))

# Making sure the data looks good.
df2t2_joint.head()

       country sex_female  year  monthly_usd_female sex_male  monthly_usd_male
0  Afghanistan     Female  2014               96.38     Male            159.57
1  Afghanistan     Female  2020              141.16     Male            174.96
2      Albania     Female  2012             2958.61     Male           3408.75
3      Albania     Female  2015              357.51     Male            383.91
4      Albania     Female  2016              357.28     Male            403.44

In [55]:
# Now I want to calculate the ratio of female to male.

df2t2_joint['ratio'] = df2t2_joint['monthly_usd_female'] / df2t2_joint['monthly_usd_male']
df2t2_joint

,country,sex_female,year,monthly_usd_female,sex_male,monthly_usd_male,ratio
0,Afghanistan,Female,2014,96.38,Male,159.57,0.603998
1,Afghanistan,Female,2020,141.16,Male,174.96,0.806813
2,Albania,Female,2012,2958.61,Male,3408.75,0.867946
3,Albania,Female,2015,357.51,Male,383.91,0.931234
4,Albania,Female,2016,357.28,Male,403.44,0.885584
5,Albania,Female,2017,386.38,Male,431.50,0.895435
6,Albania,Female,2018,439.77,Male,492.47,0.892988
7,Albania,Female,2019,449.80,Male,500.13,0.899366
8,Albania,Female,2020,475.65,Male,509.13,0.934241
9,Argentina,Female,2011,643.24,Male,861.95,0.746261
10,Argentina,Female,2012,728.45,Male,972.04,0.749403
11,Argentina,Female,2013,769.04,Male,1024.66,0.750532
12,Argentina,Female,2014,674.42,Male,898.34,0.750740
13,Argentina,Female,2017,740.12,Male,989.15,0.748238
14,Argentina,Female,2018,554.54,Male,745.25,0.744099
15,Argentina,Female,2019,454.05,Male,596.64,0.761012
16,Argentina,Female,2020,445.54,Male,573.56,0.776798
17,Argentina,Female,2021,460.65,Male,617.21,0.746342
18,Armenia,Female,2014,179.49,Male,276.04,0.650232
19,Armenia,Female,2015,166.44,Male,249.38,0.667415
20,Armenia,Female,2016,165.54,Male,248.00,0.667500
21,Armenia,Female,2017,174.89,Male,252.85,0.691675
22,Armenia,Female,2018,184.67,Male,262.98,0.702221
23,Armenia,Female,2019,204.42,Male,282.79,0.722869
24,Armenia,Female,2020,205.68,Male,293.26,0.701357
25,Armenia,Female,2013,171.56,Male,270.29,0.634726
26,Australia,Female,2011,3595.31,Male,5427.13,0.662470
27,Australia,Female,2012,3680.18,Male,5798.68,0.634658
28,Australia,Female,2013,3465.94,Male,5509.57,0.629076
29,Australia,Female,2015,2873.78,Male,4357.57,0.659491
30,Australia,Female,2017,3175.85,Male,4741.24,0.669835
31,Australia,Female,2019,3177.14,Male,4497.27,0.706460
32,Australia,Female,2020,3209.09,Male,4569.57,0.702274
33,Australia,Female,2014,3669.73,Male,5580.71,0.657574
34,Australia,Female,2016,3251.65,Male,4689.82,0.693342
35,Australia,Female,2018,4169.17,Male,4934.94,0.844827
36,Austria,Female,2016,3224.50,Male,4903.78,0.657554
37,Austria,Female,2020,3826.85,Male,5470.13,0.699590
38,Austria,Female,2011,2572.33,Male,4175.87,0.615999
39,Austria,Female,2012,2442.38,Male,3966.14,0.615808
40,Austria,Female,2013,2561.94,Male,4160.99,0.615704
41,Austria,Female,2015,2236.78,Male,3569.30,0.626672
42,Austria,Female,2017,2373.46,Male,3756.19,0.631880
43,Austria,Female,2018,2572.12,Male,4055.40,0.634246
44,Austria,Female,2019,2526.65,Male,3965.18,0.637209
45,Azerbaijan,Female,2013,331.28,Male,697.10,0.475226
46,Azerbaijan,Female,2014,382.10,Male,698.54,0.546998
47,Azerbaijan,Female,2015,303.06,Male,562.19,0.539070
48,Azerbaijan,Female,2016,198.53,Male,394.56,0.503168
49,Azerbaijan,Female,2017,195.04,Male,385.26,0.506256
50,Azerbaijan,Female,2018,212.23,Male,394.23,0.538341
51,Azerbaijan,Female,2019,261.41,Male,449.00,0.582205
52,Azerbaijan,Female,2020,311.65,Male,486.18,0.641018
53,Azerbaijan,Female,2021,328.24,Male,498.65,0.658257
54,Burundi,Female,2020,199.65,Male,241.23,0.827633
55,Belgium,Female,2012,4576.28,Male,6265.85,0.730353
56,Belgium,Female,2019,4748.65,Male,6364.87,0.746072
57,Belgium,Female,2020,5013.82,Male,6578.70,0.762129
58,Belgium,Female,2011,3369.92,Male,4359.60,0.772988
59,Belgium,Female,2013,3357.48,Male,4264.59,0.787293
60,Belgium,Female,2014,3435.50,Male,4307.00,0.797655
61,Belgium,Female,2015,2906.92,Male,3631.44,0.800487
62,Belgium,Female,2016,2903.41,Male,3636.18,0.798478
63,Belgium,Female,2017,3023.03,Male,3782.17,0.799285
64,Belgium,Female,2018,3228.73,Male,4032.96,0.800586
65,Burkina Faso,Female,2018,149.87,Male,212.99,0.703648
66,Bangladesh,Female,2016,154.28,Male,167.47,0.921240
67,Bangladesh,Female,2017,137.48,Male,149.74,0.918125
68,Bulgaria,Female,2012,263.01,Male,322.65,0.815156
69,Bulgaria,Female,2019,368.91,Male,428.44,0.861054
70,Bulgaria,Female,2020,407.34,Male,467.93,0.870515
71,Bosnia and Herzegovina,Female,2011,468.00,Male,520.61,0.898945
72,Bosnia and Herzegovina,Female,2012,431.61,Male,474.43,0.909744
73,Bosnia and Herzegovina,Female,2013,455.65,Male,515.31,0.884225
74,Bosnia and Herzegovina,Female,2014,469.11,Male,529.43,0.886066
75,Bosnia and Herzegovina,Female,2015,387.35,Male,437.37,0.885635
76,Bosnia and Herzegovina,Female,2016,385.56,Male,440.27,0.875735
77,Bosnia and Herzegovina,Female,2020,648.08,Male,762.85,0.849551
78,Bosnia and Herzegovina,Female,2021,714.21,Male,813.76,0.877667
79,Belarus,Female,2011,406.24,Male,551.52,0.736583
80,Belarus,Female,2016,283.18,Male,398.28,0.711007
81,Belarus,Female,2019,419.36,Male,586.87,0.714571
82,Belarus,Female,2021,461.54,Male,649.00,0.711156
83,Belize,Female,2014,681.64,Male,704.35,0.967758
84,Belize,Female,2015,591.16,Male,603.97,0.978790
85,Belize,Female,2016,565.96,Male,586.44,0.965077
86,Belize,Female,2017,584.42,Male,605.87,0.964596
87,Belize,Female,2018,576.78,Male,628.16,0.918206
88,Belize,Female,2019,632.53,Male,636.06,0.994450
89,Belize,Female,2020,450.00,Male,510.00,0.882353
90,Bermuda,Female,2012,5732.20,Male,6015.60,0.952889
91,Bermuda,Female,2013,6091.50,Male,6329.60,0.962383
92,Bolivia,Female,2016,363.97,Male,482.16,0.754874
93,Bolivia,Female,2017,376.56,Male,487.77,0.772003
94,Bolivia,Female,2018,388.93,Male,489.92,0.793864
95,Bolivia,Female,2019,389.93,Male,491.40,0.793508
96,Bolivia,Female,2021,392.24,Male,476.18,0.823722
97,Bolivia,Female,2011,236.27,Male,327.91,0.720533
98,Bolivia,Female,2012,269.26,Male,377.52,0.713234
99,Bolivia,Female,2013,303.69,Male,424.93,0.714682
100,Bolivia,Female,2014,323.23,Male,435.02,0.743023
101,Bolivia,Female,2015,356.49,Male,441.54,0.807379
102,Bolivia,Female,2020,447.74,Male,505.79,0.885229
103,Brazil,Female,2012,589.20,Male,749.09,0.786554
104,Brazil,Female,2013,573.48,Male,722.11,0.794173
105,Brazil,Female,2014,580.99,Male,743.81,0.781100
106,Brazil,Female,2015,451.52,Male,566.98,0.796360
107,Brazil,Female,2016,489.69,Male,604.53,0.810034
108,Brazil,Female,2021,406.58,Male,482.19,0.843195
109,Brazil,Female,2011,619.79,Male,798.53,0.776164
110,Brazil,Female,2017,792.78,Male,930.93,0.851600
111,Brazil,Female,2018,715.58,Male,834.68,0.857311
112,Brazil,Female,2019,678.14,Male,780.52,0.868831
113,Brazil,Female,2020,525.45,Male,599.57,0.876378
114,Barbados,Female,2016,1310.78,Male,1376.23,0.952443
115,Brunei Darussalam,Female,2014,1329.61,Male,1489.42,0.892703
116,Bhutan,Female,2018,201.43,Male,242.20,0.831668
117,Bhutan,Female,2019,255.70,Male,282.93,0.903757
118,Bhutan,Female,2020,239.88,Male,281.33,0.852664
119,Botswana,Female,2019,393.74,Male,566.49,0.695052
120,Botswana,Female,2020,406.39,Male,509.60,0.797469
121,Canada,Female,2011,3142.13,Male,4175.59,0.752500
122,Canada,Female,2012,3206.89,Male,4269.71,0.751079
123,Canada,Female,2013,3182.71,Male,4224.09,0.753466
124,Canada,Female,2014,3019.86,Male,4008.46,0.753372
125,Switzerland,Female,2011,4200.45,Male,7204.96,0.582994
126,Switzerland,Female,2012,4674.62,Male,7985.18,0.585412
127,Switzerland,Female,2013,4926.51,Male,8347.82,0.590155
128,Switzerland,Female,2016,5448.99,Male,8521.00,0.639478
129,Switzerland,Female,2017,5363.78,Male,8218.22,0.652669
130,Switzerland,Female,2018,5415.27,Male,8311.49,0.651540
131,Switzerland,Female,2019,5070.32,Male,8111.94,0.625044
132,Switzerland,Female,2020,5648.46,Male,8762.55,0.644614
133,Switzerland,Female,2015,4597.97,Male,7065.81,0.650735
134,Chile,Female,2020,824.14,Male,1017.97,0.809592
135,Chile,Female,2019,986.66,Male,1291.52,0.763953
136,Côte d'Ivoire,Female,2019,185.00,Male,244.88,0.755472
137,Côte d'Ivoire,Female,2017,158.77,Male,200.71,0.791042
138,Cameroon,Female,2014,172.58,Male,310.09,0.556548
139,"Congo, Democratic Republic of the",Female,2012,72.09,Male,102.53,0.703111
140,Colombia,Female,2011,436.29,Male,462.75,0.942820
141,Colombia,Female,2012,469.07,Male,505.53,0.927878
142,Colombia,Female,2013,476.55,Male,509.97,0.934467
143,Colombia,Female,2014,452.21,Male,496.39,0.910997
144,Colombia,Female,2015,341.03,Male,368.65,0.925078
145,Colombia,Female,2016,322.90,Male,350.65,0.920861
146,Colombia,Female,2017,351.20,Male,376.94,0.931713
147,Colombia,Female,2018,367.84,Male,388.90,0.945847
148,Colombia,Female,2019,360.60,Male,379.17,0.951025
149,Colombia,Female,2021,338.51,Male,337.64,1.002577
150,Comoros,Female,2014,220.57,Male,230.73,0.955966
151,Cape Verde,Female,2015,310.65,Male,335.39,0.926235
152,Costa Rica,Female,2018,830.05,Male,878.61,0.944731
153,Costa Rica,Female,2020,930.24,Male,891.01,1.044029
154,Costa Rica,Female,2011,747.88,Male,791.68,0.944675
155,Costa Rica,Female,2012,821.88,Male,895.31,0.917984
156,Costa Rica,Female,2013,900.40,Male,980.00,0.918776
157,Costa Rica,Female,2014,844.98,Male,945.05,0.894111
158,Costa Rica,Female,2017,875.12,Male,934.37,0.936588
159,Costa Rica,Female,2019,900.52,Male,947.31,0.950608
160,Costa Rica,Female,2021,897.76,Male,924.60,0.970971
161,Costa Rica,Female,2015,928.33,Male,1017.30,0.912543
162,Costa Rica,Female,2016,929.46,Male,939.31,0.989514
163,Cyprus,Female,2011,2496.39,Male,3693.09,0.675962
164,Cyprus,Female,2012,2418.92,Male,3552.80,0.680849
165,Cyprus,Female,2013,2509.94,Male,3551.19,0.706788
166,Cyprus,Female,2015,1954.61,Male,2682.60,0.728625
167,Cyprus,Female,2016,1928.04,Male,2648.32,0.728024
168,Cyprus,Female,2017,2020.67,Male,2560.42,0.789195
169,Cyprus,Female,2019,1976.24,Male,2704.15,0.730817
170,Cyprus,Female,2020,2166.03,Male,2916.95,0.742567
171,Cyprus,Female,2018,1920.23,Male,2242.63,0.856240
172,Czechia,Female,2011,1250.74,Male,1606.64,0.778482
173,Czechia,Female,2012,1149.07,Male,1474.81,0.779131
174,Czechia,Female,2013,1161.39,Male,1483.14,0.783062
175,Czechia,Female,2014,1117.81,Male,1431.82,0.780692
176,Czechia,Female,2015,979.48,Male,1253.80,0.781209
177,Czechia,Female,2016,1035.56,Male,1311.99,0.789305
178,Czechia,Female,2017,1163.01,Male,1467.00,0.792781
179,Czechia,Female,2018,1363.42,Male,1703.09,0.800557
180,Czechia,Female,2019,1405.75,Male,1731.14,0.812037
181,Czechia,Female,2020,1497.44,Male,1793.00,0.835159
182,Germany,Female,2011,2561.52,Male,4216.53,0.607495
183,Germany,Female,2012,2406.38,Male,4027.65,0.597465
184,Germany,Female,2013,2592.63,Male,4250.34,0.609982
185,Germany,Female,2015,2295.57,Male,3750.04,0.612145
186,Germany,Female,2016,2371.19,Male,3733.96,0.635034
187,Germany,Female,2017,2478.65,Male,3828.60,0.647404
188,Germany,Female,2019,2706.57,Male,4058.18,0.666942
189,Germany,Female,2018,3327.93,Male,4199.47,0.792464
190,Djibouti,Female,2017,542.61,Male,536.20,1.011954
191,Denmark,Female,2011,696.97,Male,810.19,0.860255
192,Denmark,Female,2012,661.67,Male,780.73,0.847502
193,Denmark,Female,2013,691.90,Male,832.21,0.831401
194,Denmark,Female,2015,592.67,Male,724.47,0.818074
195,Denmark,Female,2016,596.78,Male,718.54,0.830545
196,Denmark,Female,2017,608.17,Male,754.97,0.805555
197,Denmark,Female,2018,646.91,Male,803.02,0.805596
198,Denmark,Female,2019,631.93,Male,778.31,0.811926
199,Denmark,Female,2020,730.10,Male,876.44,0.833029
200,Dominican Republic,Female,2015,277.71,Male,300.99,0.922655
201,Dominican Republic,Female,2016,279.70,Male,307.82,0.908648
202,Dominican Republic,Female,2017,294.58,Male,316.84,0.929744
203,Dominican Republic,Female,2018,304.97,Male,339.09,0.899378
204,Dominican Republic,Female,2019,314.16,Male,343.43,0.914772
205,Dominican Republic,Female,2020,284.45,Male,312.07,0.911494
206,Dominican Republic,Female,2021,292.60,Male,322.99,0.905910
207,Dominican Republic,Female,2011,297.87,Male,336.93,0.884071
208,Dominican Republic,Female,2012,322.30,Male,350.73,0.918940
209,Dominican Republic,Female,2013,300.60,Male,336.73,0.892703
210,Dominican Republic,Female,2014,297.10,Male,339.18,0.875936
211,Ecuador,Female,2011,382.19,Male,388.83,0.982923
212,Ecuador,Female,2012,413.46,Male,406.08,1.018174
213,Ecuador,Female,2013,452.52,Male,449.94,1.005734
214,Ecuador,Female,2014,489.58,Male,481.81,1.016127
215,Ecuador,Female,2015,499.78,Male,497.78,1.004018
216,Ecuador,Female,2016,495.97,Male,499.11,0.993709
217,Ecuador,Female,2017,500.61,Male,499.82,1.001581
218,Ecuador,Female,2018,519.42,Male,512.11,1.014274
219,Ecuador,Female,2019,524.58,Male,505.55,1.037642
220,Ecuador,Female,2020,525.57,Male,446.53,1.177009
221,Ecuador,Female,2021,507.66,Male,469.79,1.080610
222,Egypt,Female,2015,218.85,Male,241.19,0.907376
223,Egypt,Female,2020,148.14,Male,180.75,0.819585
224,Egypt,Female,2016,367.12,Male,414.63,0.885416
225,Egypt,Female,2017,239.84,Male,258.84,0.926596
226,Egypt,Female,2018,249.07,Male,272.95,0.912511
227,Egypt,Female,2019,314.99,Male,334.36,0.942068
228,Egypt,Female,2011,321.60,Male,366.77,0.876844
229,Egypt,Female,2012,400.26,Male,426.68,0.938080
230,Egypt,Female,2013,415.70,Male,447.72,0.928482
231,Spain,Female,2019,2373.72,Male,3041.73,0.780385
232,Spain,Female,2020,2683.48,Male,3281.60,0.817735
233,Spain,Female,2011,2228.59,Male,2864.70,0.777949
234,Spain,Female,2012,2049.85,Male,2677.17,0.765678
235,Spain,Female,2013,2153.69,Male,2791.84,0.771423
236,Spain,Female,2014,2149.65,Male,2824.21,0.761151
237,Spain,Female,2015,1823.81,Male,2354.91,0.774471
238,Spain,Female,2016,1838.57,Male,2297.54,0.800234
239,Spain,Female,2017,1939.66,Male,2484.17,0.780808
240,Spain,Female,2018,2067.85,Male,2631.17,0.785905
241,Estonia,Female,2011,1186.17,Male,1754.97,0.675892
242,Estonia,Female,2012,1179.60,Male,1740.41,0.677771
243,Estonia,Female,2013,1288.58,Male,1978.96,0.651140
244,Estonia,Female,2015,1350.42,Male,1834.38,0.736172
245,Estonia,Female,2016,1371.63,Male,1897.35,0.722919
246,Estonia,Female,2017,1468.46,Male,1891.95,0.776162
247,Estonia,Female,2019,1691.02,Male,2111.45,0.800881
248,Estonia,Female,2020,1941.04,Male,2455.60,0.790454
249,Estonia,Female,2014,1203.62,Male,1699.15,0.708366
250,Estonia,Female,2018,1387.62,Male,1720.65,0.806451
251,Ethiopia,Female,2013,55.81,Male,81.43,0.685374
252,Finland,Female,2012,4152.83,Male,5351.77,0.775973
253,Finland,Female,2016,4073.58,Male,5074.12,0.802815
254,Finland,Female,2011,3575.93,Male,4576.75,0.781325
255,Finland,Female,2013,3611.15,Male,4603.26,0.784477
256,Finland,Female,2014,3629.46,Male,4591.30,0.790508
257,Finland,Female,2015,3026.75,Male,3762.36,0.804482
258,Finland,Female,2017,3098.72,Male,3865.77,0.801579
259,Finland,Female,2018,3273.61,Male,4074.29,0.803480
260,Finland,Female,2019,3158.04,Male,3930.48,0.803474
261,Finland,Female,2020,3286.10,Male,4054.80,0.810422
262,Fiji,Female,2011,503.15,Male,520.33,0.966982
263,Fiji,Female,2016,493.53,Male,513.23,0.961616
264,France,Female,2011,3595.83,Male,5057.85,0.710940
265,France,Female,2012,3454.75,Male,4919.30,0.702285
266,France,Female,2013,3692.39,Male,5116.73,0.721631
267,France,Female,2015,3132.02,Male,4525.52,0.692080
268,France,Female,2016,3240.49,Male,4562.20,0.710291
269,France,Female,2017,3333.46,Male,4740.85,0.703136
270,France,Female,2018,3534.13,Male,4936.34,0.715941
271,France,Female,2019,3490.51,Male,4819.30,0.724277
272,France,Female,2020,4242.97,Male,6036.61,0.702873
273,United Kingdom,Female,2014,4313.43,Male,6821.13,0.632363
274,United Kingdom,Female,2011,2613.19,Male,4148.10,0.629973
275,United Kingdom,Female,2012,2619.08,Male,4091.32,0.640155
276,United Kingdom,Female,2013,2649.84,Male,4156.89,0.637457
277,United Kingdom,Female,2015,2665.97,Male,4068.47,0.655276
278,United Kingdom,Female,2016,2437.10,Male,3711.68,0.656603
279,United Kingdom,Female,2017,2384.88,Male,3626.88,0.657557
280,United Kingdom,Female,2018,2552.26,Male,3867.75,0.659882
281,United Kingdom,Female,2019,2549.00,Male,3788.40,0.672843
282,United Kingdom,Female,2020,2616.67,Male,3787.18,0.690928
283,Georgia,Female,2017,306.91,Male,477.14,0.643228
284,Ghana,Female,2015,191.99,Male,271.01,0.708424
285,Ghana,Female,2013,256.18,Male,347.77,0.736636
286,Ghana,Female,2017,64.41,Male,197.15,0.326706
287,Guinea,Female,2019,162.84,Male,201.01,0.810109
288,Gambia,Female,2012,86.21,Male,117.06,0.736460
289,Gambia,Female,2018,77.46,Male,84.75,0.913982
290,Guinea-Bissau,Female,2018,129.23,Male,175.03,0.738331
291,Greece,Female,2011,1347.44,Male,1556.39,0.865747
292,Greece,Female,2012,1126.48,Male,1307.84,0.861329
293,Greece,Female,2013,1098.13,Male,1282.26,0.856402
294,Greece,Female,2015,886.92,Male,1024.38,0.865812
295,Greece,Female,2016,892.94,Male,1031.74,0.865470
296,Greece,Female,2017,918.20,Male,1052.75,0.872192
297,Greece,Female,2018,973.22,Male,1108.33,0.878096
298,Greece,Female,2019,912.60,Male,1057.90,0.862652
299,Greece,Female,2020,936.72,Male,1091.03,0.858565
300,Guatemala,Female,2011,249.62,Male,292.49,0.853431
301,Guatemala,Female,2012,281.84,Male,292.05,0.965040
302,Guatemala,Female,2013,303.49,Male,317.07,0.957170
303,Guatemala,Female,2014,323.30,Male,337.72,0.957302
304,Guatemala,Female,2015,344.17,Male,326.19,1.055121
305,Guatemala,Female,2016,332.76,Male,343.04,0.970033
306,Guatemala,Female,2017,356.02,Male,353.36,1.007528
307,Guatemala,Female,2018,348.16,Male,356.57,0.976414
308,Guatemala,Female,2019,359.20,Male,356.61,1.007263
309,Guatemala,Female,2021,304.61,Male,311.47,0.977975
310,Guyana,Female,2018,330.05,Male,396.55,0.832304
311,Guyana,Female,2019,358.72,Male,416.76,0.860735
312,"Hong Kong, China",Female,2011,1156.22,Male,1670.09,0.692310
313,"Hong Kong, China",Female,2012,1289.26,Male,1804.96,0.714287
314,"Hong Kong, China",Female,2013,1353.79,Male,1933.99,0.699998
315,"Hong Kong, China",Female,2014,1418.61,Male,1934.46,0.733336
316,"Hong Kong, China",Female,2015,1509.34,Male,2128.55,0.709093
317,"Hong Kong, China",Female,2016,1545.94,Male,2318.92,0.666664
318,Honduras,Female,2011,423.87,Male,372.92,1.136624
319,Honduras,Female,2012,386.08,Male,340.41,1.134162
320,Honduras,Female,2013,332.97,Male,278.42,1.195927
321,Honduras,Female,2014,352.93,Male,299.52,1.178319
322,Honduras,Female,2015,328.17,Male,290.45,1.129867
323,Honduras,Female,2016,333.85,Male,293.72,1.136627
324,Honduras,Female,2017,306.47,Male,285.86,1.072098
325,Honduras,Female,2018,306.07,Male,264.35,1.157821
326,Honduras,Female,2019,320.89,Male,288.37,1.112772
327,Honduras,Female,2020,380.63,Male,313.70,1.213357
328,Croatia,Female,2011,215.34,Male,250.23,0.860568
329,Croatia,Female,2012,195.89,Male,225.26,0.869617
330,Croatia,Female,2013,194.22,Male,221.69,0.876088
331,Croatia,Female,2015,171.50,Male,197.75,0.867257
332,Croatia,Female,2016,168.64,Male,198.31,0.850386
333,Croatia,Female,2017,182.83,Male,220.16,0.830441
334,Croatia,Female,2018,193.70,Male,236.79,0.818024
335,Croatia,Female,2019,197.03,Male,240.31,0.819899
336,Croatia,Female,2020,201.02,Male,260.96,0.770310
337,Hungary,Female,2017,2.82,Male,3.25,0.867692
338,Hungary,Female,2019,2.82,Male,3.36,0.839286
339,Hungary,Female,2020,2.89,Male,3.36,0.860119
340,Hungary,Female,2014,981.51,Male,1163.83,0.843345
341,Hungary,Female,2018,1056.59,Male,1239.36,0.852529
342,Hungary,Female,2011,1043.27,Male,1248.63,0.835532
343,Hungary,Female,2012,944.35,Male,1156.26,0.816728
344,Hungary,Female,2013,989.60,Male,1184.07,0.835761
345,Hungary,Female,2015,840.34,Male,1013.99,0.828746
346,Hungary,Female,2016,859.79,Male,1070.35,0.803279
347,Indonesia,Female,2012,129.36,Male,161.39,0.801537
348,Indonesia,Female,2013,128.25,Male,161.38,0.794708
349,Indonesia,Female,2014,120.77,Male,154.54,0.781481
350,Indonesia,Female,2015,119.32,Male,143.69,0.830399
351,Indonesia,Female,2016,137.57,Male,170.71,0.805870
352,Indonesia,Female,2017,154.09,Male,195.82,0.786896
353,Indonesia,Female,2019,154.22,Male,197.67,0.780189
354,Indonesia,Female,2020,149.95,Male,188.76,0.794395
355,Indonesia,Female,2021,152.17,Male,187.27,0.812570
356,India,Female,2018,185.45,Male,248.74,0.745558
357,India,Female,2019,189.24,Male,244.72,0.773292
358,Ireland,Female,2011,3999.01,Male,5710.75,0.700260
359,Ireland,Female,2012,3737.80,Male,5135.79,0.727795
360,Ireland,Female,2013,4014.38,Male,5713.41,0.702624
361,Ireland,Female,2015,3269.52,Male,4676.85,0.699086
362,Ireland,Female,2016,3409.63,Male,4747.90,0.718134
363,Ireland,Female,2017,3579.50,Male,4836.13,0.740158
364,Ireland,Female,2019,3792.80,Male,5115.42,0.741444
365,Ireland,Female,2020,3819.92,Male,5285.73,0.722685
366,Ireland,Female,2018,3938.48,Male,4611.63,0.854032
367,Iceland,Female,2011,17.09,Male,26.70,0.640075
368,Iceland,Female,2012,16.94,Male,26.24,0.645579

In [58]:
# Cleaning up the final DataFrame and dropping redundant columns
final_df = df2t2_joint[['country', 'year', 'ratio']]

# Checking it looks good.
final_df.head()

       country  year     ratio
0  Afghanistan  2014  0.603998
1  Afghanistan  2020  0.806813
2      Albania  2012  0.867946
3      Albania  2015  0.931234
4      Albania  2016  0.885584

In [59]:
final_df.shape

(817, 3)

In [118]:
# First, I remove multi-level indices before merging.

diff_country_df.to_clipboard(index=False)
diff_country_df=pd.read_clipboard(sep='\t')
diff_country_df = diff_country_df.rename(columns= {'year' : 'min_year',
                        'year.1' : 'max_year'})

diff_country_df = diff_country_df.dropna()

In [119]:
diff_country_df.head()

       country min_year max_year
1  Afghanistan     2014     2020
2      Albania     2012     2020
3    Argentina     2011     2021
4      Armenia     2013     2020
5    Australia     2011     2020

In [120]:
# Checking data types of the columns.
diff_country_df.dtypes

country     object
min_year    object
max_year    object
dtype: object

In [124]:
# Looks like years got converted into strings. I will now convert them into integers.

diff_country_df['min_year'] = diff_country_df['min_year'].astype(int)
diff_country_df['max_year'] = diff_country_df['max_year'].astype(int)

diff_country_df.dtypes

country     object
min_year     int64
max_year     int64
dtype: object

In [125]:
# Check for the data types in the final_df

final_df.dtypes

# Seems correct, no conversion needed.

country     object
year         int64
ratio      float64
dtype: object

In [128]:
# First, I join with the ratio DataFrame on min year.

min_year_final = final_df.merge(diff_country_df, left_on=('country', 'year'), right_on=('country', 'min_year'))
min_year_final.head()

       country  year     ratio  min_year  max_year
0  Afghanistan  2014  0.603998      2014      2020
1      Albania  2012  0.867946      2012      2020
2    Argentina  2011  0.746261      2011      2021
3      Armenia  2013  0.634726      2013      2020
4    Australia  2011  0.662470      2011      2020

In [129]:
# Do the same for the max year.

max_year_final = final_df.merge(diff_country_df, left_on=('country', 'year'), right_on=('country', 'max_year'))
max_year_final.head()

       country  year     ratio  min_year  max_year
0  Afghanistan  2020  0.806813      2014      2020
1      Albania  2020  0.934241      2012      2020
2    Argentina  2021  0.746342      2011      2021
3      Armenia  2020  0.701357      2013      2020
4    Australia  2020  0.702274      2011      2020

In [134]:
# Now I can do a concatenation on these two.

frames = [min_year_final, max_year_final]
concat_df = pd.concat(frames)

# Next steps: reset index to be able to order by country and year.
concat_df = concat_df.reset_index()
del concat_df['index']

In [138]:
final_total_df = concat_df.sort_values(by=(['country', 'year']))

del final_total_df['min_year']
del final_total_df['max_year']

In [146]:
# Above I produced a DataFrame with data for countries that have two different years available.
# Now I want to add data for countries that only have 1 year of data available.

final_total_df

                          country  year     ratio
0                     Afghanistan  2014  0.603998
109                   Afghanistan  2020  0.806813
1                         Albania  2012  0.867946
110                       Albania  2020  0.934241
2                       Argentina  2011  0.746261
111                     Argentina  2021  0.746342
3                         Armenia  2013  0.634726
112                       Armenia  2020  0.701357
4                       Australia  2011  0.662470
113                     Australia  2020  0.702274
5                         Austria  2011  0.615999
114                       Austria  2020  0.699590
6                      Azerbaijan  2013  0.475226
115                    Azerbaijan  2021  0.658257
8                      Bangladesh  2016  0.921240
117                    Bangladesh  2017  0.918125
11                        Belarus  2011  0.736583
120                       Belarus  2021  0.711156
7                         Belgium  2011  0.772988
116                       Belgium  2020  0.762129
12                         Belize  2014  0.967758
121                        Belize  2020  0.882353
13                        Bermuda  2012  0.952889
122                       Bermuda  2013  0.962383
16                         Bhutan  2018  0.831668
125                        Bhutan  2020  0.852664
14                        Bolivia  2011  0.720533
123                       Bolivia  2021  0.823722
10         Bosnia and Herzegovina  2011  0.898945
119        Bosnia and Herzegovina  2021  0.877667
17                       Botswana  2019  0.695052
126                      Botswana  2020  0.797469
15                         Brazil  2011  0.776164
124                        Brazil  2021  0.843195
9                        Bulgaria  2012  0.815156
118                      Bulgaria  2020  0.870515
55                       Cambodia  2011  0.723120
164                      Cambodia  2019  0.876339
18                         Canada  2011  0.752500
127                        Canada  2014  0.753372
20                          Chile  2019  0.763953
129                         Chile  2020  0.809592
22                       Colombia  2011  0.942820
131                      Colombia  2021  1.002577
23                     Costa Rica  2011  0.944675
132                    Costa Rica  2021  0.970971
44                        Croatia  2011  0.860568
153                       Croatia  2020  0.770310
24                         Cyprus  2011  0.675962
133                        Cyprus  2020  0.742567
25                        Czechia  2011  0.778482
134                       Czechia  2020  0.835159
21                  Côte d'Ivoire  2017  0.791042
130                 Côte d'Ivoire  2019  0.755472
27                        Denmark  2011  0.860255
136                       Denmark  2020  0.833029
28             Dominican Republic  2011  0.884071
137            Dominican Republic  2021  0.905910
29                        Ecuador  2011  0.982923
138                       Ecuador  2021  1.080610
30                          Egypt  2011  0.876844
139                         Egypt  2020  0.819585
90                    El Salvador  2011  0.982919
199                   El Salvador  2019  0.951484
32                        Estonia  2011  0.675892
141                       Estonia  2020  0.790454
34                           Fiji  2011  0.966982
143                          Fiji  2016  0.961616
33                        Finland  2011  0.781325
142                       Finland  2020  0.810422
35                         France  2011  0.710940
144                        France  2020  0.702873
38                         Gambia  2012  0.736460
147                        Gambia  2018  0.913982
26                        Germany  2011  0.607495
135                       Germany  2019  0.666942
37                          Ghana  2013  0.736636
146                         Ghana  2017  0.326706
39                         Greece  2011  0.865747
148                        Greece  2020  0.858565
40                      Guatemala  2011  0.853431
149                     Guatemala  2021  0.977975
41                         Guyana  2018  0.832304
150                        Guyana  2019  0.860735
43                       Honduras  2011  1.136624
152                      Honduras  2020  1.213357
42               Hong Kong, China  2011  0.692310
151              Hong Kong, China  2016  0.666664
45                        Hungary  2011  0.835532
154                       Hungary  2020  0.860119
49                        Iceland  2011  0.640075
158                       Iceland  2019  0.825665
47                          India  2018  0.745558
156                         India  2019  0.773292
46                      Indonesia  2012  0.801537
155                     Indonesia  2021  0.812570
48                        Ireland  2011  0.700260
157                       Ireland  2020  0.722685
50                         Israel  2011  0.661588
159                        Israel  2018  0.683788
51                          Italy  2011  0.767594
160                         Italy  2019  0.751584
52                        Jamaica  2011  0.907795
161                       Jamaica  2014  0.994431
53                         Jordan  2016  0.903358
162                        Jordan  2020  1.053721
54                     Kazakhstan  2011  0.679888
163                    Kazakhstan  2020  0.750148
56             Korea, Republic of  2011  0.640400
165            Korea, Republic of  2021  0.660513
60                         Latvia  2011  0.826839
169                        Latvia  2020  0.795880
58                      Lithuania  2015  0.884788
167                     Lithuania  2020  0.821626
59                     Luxembourg  2011  0.676104
168                    Luxembourg  2020  0.792417
61                   Macau, China  2011  0.754541
170                  Macau, China  2018  0.882355
62                     Madagascar  2012  0.693728
171                    Madagascar  2015  0.877158
70                       Malaysia  2011  0.950595
179                      Malaysia  2020  0.975032
63                       Maldives  2016  0.790673
172                      Maldives  2019  0.773081
65                           Mali  2013  0.612118
174                          Mali  2020  0.709953
66                          Malta  2011  0.827584
175                         Malta  2020  0.820881
69                      Mauritius  2011  0.680724
178                     Mauritius  2019  0.772868
64                         Mexico  2011  0.864307
173                        Mexico  2021  0.864934
68                       Mongolia  2011  0.811352
177                      Mongolia  2021  0.836702
67                        Myanmar  2015  0.738996
176                       Myanmar  2020  0.891877
71                        Namibia  2012  0.821774
180                       Namibia  2018  0.898215
74                    Netherlands  2011  0.661857
183                   Netherlands  2020  0.680357
73                      Nicaragua  2012  0.917128
182                     Nicaragua  2014  1.145451
72                        Nigeria  2011  0.864396
181                       Nigeria  2019  0.629762
75                         Norway  2011  0.872289
184                        Norway  2020  0.875265
76                       Pakistan  2011  0.634622
185                      Pakistan  2021  0.810633
77                         Panama  2011  0.945187
186                        Panama  2021  1.101188
82                       Paraguay  2011  0.788483
191                      Paraguay  2021  0.908535
78                           Peru  2011  0.764853
187                          Peru  2021  0.860576
79                    Philippines  2011  1.030981
188                   Philippines  2020  1.087103
80                         Poland  2011  0.869717
189                        Poland  2020  0.830105
81                       Portugal  2011  0.823799
190                      Portugal  2020  0.852573
83                          Qatar  2011  0.773158
192                         Qatar  2020  0.935704
84                        Romania  2011  0.880845
193                       Romania  2020  0.928258
85             Russian Federation  2011  0.679100
194            Russian Federation  2019  0.720917
86                         Rwanda  2014  0.696261
195                        Rwanda  2017  0.620717
106                         Samoa  2012  0.942674
215                         Samoa  2017  1.104368
87                   Saudi Arabia  2015  0.918259
196                  Saudi Arabia  2020  0.912027
88                        Senegal  2018  0.669887
197                       Senegal  2019  0.591623
91                         Serbia  2013  0.913110
200                        Serbia  2021  0.872676
89                      Singapore  2011  0.900610
198                     Singapore  2020  0.926890
92                       Slovakia  2011  0.757762
201                      Slovakia  2020  0.808533
93                       Slovenia  2011  0.954210
202                      Slovenia  2020  0.851703
107                  South Africa  2011  0.783984
216                  South Africa  2019  0.866498
31                          Spain  2011  0.777949
140                         Spain  2020  0.817735
57                      Sri Lanka  2011  0.831765
166                     Sri Lanka  2019  0.795076
94                         Sweden  2011  0.749578
203                        Sweden  2020  0.902375
19                    Switzerland  2011  0.582994
128                   Switzerland  2020  0.644614
100  Tanzania, United Republic of  2014  0.803334
209  Tanzania, United Republic of  2020  0.958386
96                       Thailand  2011  0.946145
205                      Thailand  2020  1.031657
97                    Timor-Leste  2013  0.920257
206                   Timor-Leste  2016  3.144198
95                           Togo  2011  0.666028
204                          Togo  2017  0.873278
98            Trinidad and Tobago  2011  0.907256
207           Trinidad and Tobago  2016  0.883801
99                        Türkiye  2011  0.947260
208                       Türkiye  2021  0.912511
101                        Uganda  2012  0.636424
210                        Uganda  2017  0.600029
102                       Ukraine  2012  0.786657
211                       Ukraine  2016  0.768920
36                 United Kingdom  2011  0.629973
145                United Kingdom  2020  0.690928
104                 United States  2011  0.750033
213                 United States  2021  0.789898
103                       Uruguay  2011  0.754461
212                       Uruguay  2020  0.815898
105                      Viet Nam  2011  0.871508
214                      Viet Nam  2021  0.875763
108                        Zambia  2017  1.064562
217                        Zambia  2020  0.898512

In [150]:
# Converting the countries into a list (countries with one year of data available only).
same_country_list = (same_country_df['country']).tolist()
same_country_list

['Barbados',
 'Brunei Darussalam',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Cape Verde',
 'Chad',
 'Comoros',
 'Congo, Democratic Republic of the',
 'Djibouti',
 'Eswatini',
 'Ethiopia',
 'Georgia',
 'Guinea',
 'Guinea-Bissau',
 'Kenya',
 "Lao People's Democratic Republic",
 'Lebanon',
 'Lesotho',
 'Malawi',
 'Marshall Islands',
 'Nepal',
 'Réunion',
 'Sierra Leone',
 'Suriname',
 'Tonga',
 'Uzbekistan',
 'Yemen']

In [164]:
# Getting a subset of countries that only have one year.

final_oneyear = final_df.loc[final_df.apply(lambda x: x.country in same_country_list, axis=1)]
frames = [final_oneyear, final_total_df]
super_final_df = pd.concat(frames)
super_final_df = super_final_df.sort_values(by='country')
super_final_df.to_csv("total_df.csv")